{
 "title": "Queries failed vs ok",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Failed vs OK over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_queries_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_queries_ok)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(indexer_service_queries_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total queries per deployment",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(indexer_service_queries_total)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Failed vs OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total queries by deployment",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_service_queries_total[1m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}