{
 "title": "Graph Service Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queries Failed vs OK over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_service_queries_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_queries_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total queries by deployment per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_service_queries_total[1m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_service_channel_messages_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_channel_messages_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total Channel Messages by Servicenode per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_service_channel_messages_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Cost Model Queries over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_service_cost_model_queries_invalid)",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries)",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_failed)",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_invalid)",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  },
  {
   "title": "Total Cost Model Batch Queries by Servicenode per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_service_cost_model_batch_queries[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost Model Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_cost_model_queries_invalid[1m]))",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries[1m]))",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_failed[1m]))",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_invalid[1m]))",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  }
 ]
}