{
 "title": "Indexing Status Split",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Indexing status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect\n  g.name || (case\n        when g.pending_version = v.id then ' (P)'\n        when g.current_version = v.id then ' (C)'\n        else ' (U)' end) as subgraph_name,\n  d.id as deployment,\n  s.id as schema,\n  replace(a.node_id, '','') as nodeId,\n  d.synced::text,\n  n.name as network,\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\n        else 'ø' end) as lag\nfrom subgraphs.subgraph_deployment as d,\n     subgraphs.subgraph_deployment_assignment as a,\n     subgraphs.subgraph_version as v,\n     subgraphs.subgraph as g,\n     subgraphs.ethereum_contract_data_source as ds,\n     subgraphs.subgraph_manifest m,\n     ethereum_networks  as n,\n     deployment_schemas as s\nwhere g.id = v.subgraph\n  and v.id in (g.pending_version, g.current_version)\n  and a.id = d.id\n  and m.id = d.manifest \n  and ds.id = m.data_sources[1]\n  and s.subgraph = d.id\n  and v.deployment = d.id\n  and not d.failed\n  and n.name = ds.network\n  and not a.node_id = 'removed'\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Paused Subgraphs",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect\n  g.name || (case\n        when g.pending_version = v.id then ' (P)'\n        when g.current_version = v.id then ' (C)'\n        else ' (U)' end) as subgraph_name,\n  d.id as deployment,\n  s.id as schema,\n  replace(a.node_id,'','') as nodeid,\n  d.synced::text,\n  n.name as network,\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\n        else 'ø' end) as lag\nfrom subgraphs.subgraph_deployment as d,\n     subgraphs.subgraph_deployment_assignment as a,\n     subgraphs.subgraph_version as v,\n     subgraphs.subgraph as g,\n     subgraphs.ethereum_contract_data_source as ds,\n     subgraphs.subgraph_manifest m,\n     ethereum_networks  as n,\n     deployment_schemas as s\nwhere g.id = v.subgraph\n  and v.id in (g.pending_version, g.current_version)\n  and a.id = d.id\n  and m.id = d.manifest \n  and ds.id = m.data_sources[1]\n  and s.subgraph = d.id\n  and v.deployment = d.id\n  and not d.failed\n  and n.name = ds.network\n  and a.node_id not like 'index_node_%'\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Fatal errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  vid, block_number, subgraph_id, message, handler\nFROM subgraphs.subgraph_error\nORDER BY vid DESC"
    }
   ]
  },
  {
   "title": "Subgraph Health",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT sd.vid,sd.id,sd.network,sd.health,sd.node_id,sd.failed,sd.synced,sd.entity_count,sd.latest_ethereum_block_number,sd.ethereum_head_block_number FROM subgraphs.\"subgraph_deployment_detail\" as sd left join subgraphs.\"subgraph_manifest\" sm on (sm.id = sd.manifest) order by sd.vid"
    }
   ]
  },
  {
   "title": "Deployment schema size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT table_schema,subgraph,total_bytes, pg_size_pretty(total_bytes) AS total\r\n  FROM (\r\n  SELECT *, total_bytes-index_bytes-coalesce(toast_bytes,0) AS table_bytes FROM (\r\n      SELECT nspname AS table_schema\r\n                , ds.subgraph\r\n              , sum(pg_total_relation_size(c.oid)) AS total_bytes\r\n              , sum(pg_indexes_size(c.oid)) AS index_bytes\r\n              , sum(pg_total_relation_size(reltoastrelid)) AS toast_bytes\r\n          FROM pg_class c\r\n          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\r\n            INNER JOIN deployment_schemas ds ON ds.name = n.nspname\r\n          WHERE relkind = 'r'\r\n            GROUP BY ds.subgraph,table_schema\r\n          \r\n  ) a\r\n) a ORDER BY total_bytes DESC;"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "select replace(node_id, '', '') as nodeId,\n       count(*) as num_assigned,\n       array_agg(id) as deployments\n  from subgraphs.subgraph_deployment_assignment\n group by node_id\n order by node_id asc;\n"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nORDER BY name;"
    }
   ]
  }
 ]
}