{
 "title": "Indexing Status Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Indexing status",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\r\nselect\r\n  g.name || (case\r\n        when g.pending_version = v.id then ' (P)'\r\n        when g.current_version = v.id then ' (C)'\r\n        else ' (U)' end) as subgraph_name,\r\n  d.deployment,\r\n  s.id as schema,\r\n  replace(a.node_id, '','') as nodeId,\r\n  d.synced::text,\r\n  n.name as network,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\r\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\r\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\r\n        when n.name = 'ropsten' then ((n.head_block_number - d.latest_ethereum_block_number)/2)::text\r\n        else 'ø' end) as lag\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     subgraphs.subgraph_version as v,\r\n     subgraphs.subgraph as g,\r\n     ethereum_networks  as n,\r\n     deployment_schemas as s\r\nwhere g.id = v.subgraph\r\n  and v.id in (g.pending_version, g.current_version)\r\n  and a.id = s.id\r\n  and s.id = d.id\r\n  and v.deployment = d.deployment\r\n  and not d.failed\r\n  and n.name = s.network\r\n  and not a.node_id = 'removed'\r\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Paused Subgraphs",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\r\nselect\r\n  g.name || (case\r\n        when g.pending_version = v.id then ' (P)'\r\n        when g.current_version = v.id then ' (C)'\r\n        else ' (U)' end) as subgraph_name,\r\n  d.deployment,\r\n  s.id as schema,\r\n  replace(a.node_id,'','') as nodeid,\r\n  d.synced::text,\r\n  n.name as network,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\r\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\r\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\r\n\t\twhen n.name = 'ropsten' then ((n.head_block_number - d.latest_ethereum_block_number)/2)::text\r\n        else 'ø' end) as lag\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     subgraphs.subgraph_version as v,\r\n     subgraphs.subgraph as g,\r\n     ethereum_networks  as n,\r\n     deployment_schemas as s\r\nwhere g.id = v.subgraph\r\n  and v.id in (g.pending_version, g.current_version)\r\n  and a.id = s.id\r\n  and s.id = d.id\r\n  and v.deployment = d.deployment\r\n  and not d.failed\r\n  and n.name = s.network\r\n  and a.node_id not like 'index_node_%'\r\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Fatal errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  vid, encode(block_hash, 'hex') as Block_hash, subgraph_id, message, handler, deterministic, created_at\nFROM subgraphs.subgraph_error\nORDER BY vid DESC"
    }
   ]
  },
  {
   "title": "Subgraph Health",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tds.name as deployment_schema,\r\n\tsg.name as deployment_name,\r\n\tsd.id as deployment_id,\r\n\tsubstring(sm.repository,20,31) as git_repo,\r\n\tsda.node_id as node_id,\r\n\tsd.health as sub_health,\r\n\tsd.failed as sub_failed,\r\n\tsd.synced as sub_sync,\r\n\tsd.latest_ethereum_block_number as last_block,\r\n\tsd.entity_count as sub_entity,\r\n\tsize.total_bytes as size_total, \r\n\tsize.total_bytes as size_total_bytes, \r\n\tsd.earliest_ethereum_block_number as start_block, \r\n\tencode(sd.earliest_ethereum_block_hash, 'hex') as start_hash, \r\n\tencode(sd.latest_ethereum_block_hash, 'hex') as last_hash,\r\n\tsd.reorg_count as reorg_count, \r\n\tsd.current_reorg_depth as curr_reorg_count, \r\n\tsd.max_reorg_depth as max_reorg\r\nFROM subgraphs.\"subgraph_deployment\" as sd\r\nleft join subgraphs.\"subgraph_manifest\" as sm on (sm.id = sd.id)\r\nleft join subgraphs.\"subgraph_deployment_assignment\" as sda on (sda.id = sd.id)\r\nleft join subgraphs.\"subgraph_version\" as sv on (sv.deployment = sd.deployment)\r\nleft join subgraphs.\"subgraph\" as sg on (sv.id in (sg.current_version, sg.pending_version))\r\nleft join public.\"deployment_schemas\" as ds on (ds.subgraph = sd.deployment)\r\nleft join (\r\n\tSELECT *, total_bytes-index_bytes-coalesce(toast_bytes,0) AS table_bytes FROM (\r\n\t\tSELECT nspname AS table_schema\r\n            , ds.subgraph\r\n            , sum(pg_total_relation_size(c.oid)) AS total_bytes\r\n            , sum(pg_indexes_size(c.oid)) AS index_bytes\r\n            , sum(pg_total_relation_size(reltoastrelid)) AS toast_bytes\r\n\t\tFROM pg_class c\r\n\t\tLEFT JOIN pg_namespace n ON n.oid = c.relnamespace\r\n\t\t\tINNER JOIN deployment_schemas ds ON ds.name = n.nspname\r\n\t\tWHERE relkind = 'r'\r\n\t\t\tGROUP BY ds.subgraph,table_schema\r\n  ) a\r\n) as size on (sd.deployment = size.subgraph) order by sd.id"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select replace(node_id, '', '') as nodeId,\n       count(*) as num_assigned,\n       array_agg(id) as deployments\n  from subgraphs.subgraph_deployment_assignment\n group by node_id\n order by node_id asc;\n"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nORDER BY name;"
    }
   ]
  }
 ]
}