---
- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "no"
        update_cache: yes
        cache_valid_time: 86400 #One day

- hosts: all
  vars:
    pip_install_packages:
      - name: docker
    postgres_user: "{{ pg_graph_node_username }}"
    postgres_password: "{{ pg_graph_node_password }}"
    postgres_database: "{{ pg_graph_node_database }}"
    
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - postgres-docker

- hosts: all
  vars:
    postgres_container_name: "{{ pg_agent_service_host }}"
    postgres_volume_name: "{{ pg_agent_service_host }}_data"
    graph_node_name: "index-node"
    graph_node_role: "index-node" 
    graph_node_id: "index_node_0"
    block_ingestor: "index_node_0"
    GRAPH_NODE_ID: "index_node_0"
    postgres_user: "{{ pg_agent_service_username }}"
    postgres_password: "{{ pg_agent_service_password }}"
    postgres_database: "{{ pg_agent_service_database }}"
  roles:
    - postgres-docker
    - graph-node
    - indexer-service
    - indexer-agent
    - prometheus
    - grafana-docker

- hosts: all
  vars:
    graph_node_name: "query-node"
    graph_node_role: "query-node"
    graph_node_id: "query_node_0"
    graphnode_index_node_port: "12030"
    graphnode_http_port: "12000"
    graphnode_ws_port: "12001"
    graphnode_admin_port: "12020"
    graphnode_metrics_port: "12040"
  roles:
    - graph-node

