---
# tasks file for indexer-agent
- name: Pull indexer-agent Docker image
  docker_image:
    name: "{{ indexer_agent_image }}"
    source: pull

- name: Create network if doesn't exist
  docker_network: 
    name: "{{ indexer_agent_network }}"
    state: present
       
- name: Start indexer-agent container
  vars:
    ip_address: "{{ ansible_wg0.ipv4.address if ansible_wg0 is defined else '127.0.0.1'}}"
  docker_container:
    name: "{{ indexer_agent_name }}"
    image: "{{ indexer_agent_image }}"
    state: started
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    ulimits: nofile:10000:10000
    exposed_ports:
      - '8000'
      - '8001'
    published_ports:
      - "{{ ip_address }}:{{ indexer_agent_mgmt_port }}:8000"
      - "{{ ip_address }}:{{ indexer_agent_vector_event_server_port }}:8001"
    networks:
      - name: "{{ indexer_agent_network }}"
    network_mode: default
    env:
      INDEXER_AGENT_MNEMONIC:  "{{ operator_wallet_seed_phrase }}"
      INDEXER_AGENT_INDEXER_ADDRESS: "{{ indexer_wallet_address }}"
      INDEXER_AGENT_INDEX_NODE_IDS: "{{ index_node_ids }}" 
      INDEXER_AGENT_INJECT_DAI: "{{ indexer_agent_inject_dai }}"
      INDEXER_AGENT_ETHEREUM: "{{ ethereum_node_agent }}"
      INDEXER_AGENT_ETHEREUM_NETWORK: "{{ ethereum_network_agent }}" 
      INDEXER_AGENT_RESTAKE_REWARDS: "{{ indexer_agent_restake_rewards }}"
      INDEXER_AGENT_ALLOCATION_CLAIM_THRESHOLD: "{{ indexer_agent_allocation_claim_threshold }}" 
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: "{{ graph_node_query_endpoint }}" 
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: "{{ graph_node_status_endpoint }}" 
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: "{{ graph_node_admin_endpoint }}" 
      INDEXER_AGENT_PUBLIC_INDEXER_URL: "{{ public_indexer_url }}" 
      INDEXER_AGENT_INDEXER_GEO_COORDINATES: "{{ indexer_geo_coordinates }}" 
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: "{{ indexer_agent_network_subgraph_endpoint }}" 
      INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT: "{{ indexer_agent_network_subgraph_deployment }}"
      INDEXER_AGENT_POSTGRES_HOST: "{{ pg_agent_service_host }}" 
      INDEXER_AGENT_POSTGRES_USERNAME: "{{ pg_agent_service_username }}" 
      INDEXER_AGENT_POSTGRES_PASSWORD: "{{ pg_agent_service_password }}" 
      INDEXER_AGENT_POSTGRES_DATABASE: "{{ pg_agent_service_database }}"
      INDEXER_AGENT_VECTOR_NODE: "{{ indexer_agent_vector_node }}"
      INDEXER_AGENT_VECTOR_EVENT_SERVER: "{{ indexer_agent_vector_event_server }}"
      INDEXER_AGENT_VECTOR_EVENT_SERVER_PORT: "{{ indexer_agent_vector_event_server_port }}"
      INDEXER_AGENT_VECTOR_ROUTER: "{{ indexer_agent_vector_router }}"
      INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT: "{{ indexer_agent_collect_receipts_endpoint }}"